proxmox_config:
  url: "192.168.1.1"
  port: 8006
  realm: "pam"
  token_id: ""
  token_secret: ""
  user: ""
  password: ""
  verify_ssl: false

vms:
  - vm_id: 100
    node: px-test
    dependencies: []
    startup_parameters:
      await_running: true
      startup_timeout: 300
    healthcheck:
      target_url: "192.168.1.61"
      check_method: "ping"

  - vm_id: 301
    node: px-test
    startup_parameters:
      await_running: true
      startup_timeout: 300
    enabled: true
    dependencies:
      - 101
    healthcheck:
      target_url: "http://192.168.1.77/"
      check_method: "http"

  - vm_id: 124
    node: px-test
    dependencies:
      - 101
      - 301

