proxmox_config:
  host: ""
  token: ""
  token_value: ""
  verify_ssl: false

settings:
  auto_start_dependency: false
  auto_shutdown: true

notification_options:
  - telegram:
      token: 0
      chat_id: 0

vms:
  - vm_id: 100
    dependencies: []
    startup_parameters:
      await_running: true
      startup_timeout: 60
    healthcheck:
      target_url: "127.0.0.1"
      check_method: "ping"
