proxmox_config:
  host: ""
  token: ""
  token_value: ""
  verify_ssl: false

settings:
  auto_start_dependency: false
  auto_shutdown: true

notification_options:
  - telegram:
      token: 0
      chat_id: 0
  - email:
      smtp_server: "example.com"
      smtp_port: 587
      smtp_user: "user"
      smtp_password: "pwd"
      from_email: "pxpilot@example.com"
      to_email: "myemail@example.com"

vms:
  - vm_id: 100
    dependencies: []
    startup_parameters:
      await_running: true
      startup_timeout: 60
    healthcheck:
      target_url: "127.0.0.1"
      check_method: "ping"
