proxmox_config:
  url: "192.168.1.1"
  port: 8006
  realm: "pam"
  token_id: ""
  token_secret: ""
  user: "root@pam"
  password: "123456789"
  verify_ssl: false

notification_options:
  - telegram:
      token:
      chat_id:

vms:
  - vm_id: 100
    node: px-test
    dependencies: []
    startup_parameters:
      await_running: true
      startup_timeout: 60
    healthcheck:
      target_url: "192.168.1.2"
      check_method: "ping"

  - vm_id: 301
    node: px-test
    startup_parameters:
      await_running: true
      startup_timeout: 60
    enabled: true
    dependencies:
      - 100
    healthcheck:
      target_url: "http://192.168.1.3/"
      check_method: "http"

  - vm_id: 124
    node: px-test
    dependencies:
      - 100
      - 301


