"""healthcheck_enabled_wait_run

Revision ID: 9a1b7c452b4a
Revises: 5b805c118c47
Create Date: 2024-09-08 20:56:02.425287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1b7c452b4a'
down_revision: Union[str, None] = '5b805c118c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('healthcheck', sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
    op.add_column('vm_startup_settings', sa.Column('wait_until_running', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vm_startup_settings', 'wait_until_running')
    op.drop_column('healthcheck', 'enabled')
    # ### end Alembic commands ###
