FROM python:3.12-slim

WORKDIR /core

COPY ./requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["uvicorn", "api.main:api", "--host", "0.0.0.0", "--port", "8080", "--app-dir", "app", "--reload"]
