name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pr_check:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.12 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint
        run: |
          pip install flake8
          flake8 .
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-test.txt
      - name: Run Tests
        run: |
          pytest .
